name: merge gitlab
on:
  push:
    branches:
      - oscam-gitlab
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: merge
      run: |
        git config --global user.name "oscam-emu"
        git config --global user.email "oscam-emu@users.noreply.github.com"
        git merge origin/oscam-gitlab -m "Auto-Merge branch 'oscam-gitlab'"
        git push --follow-tags origin
